//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnockAndCheckHF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checkup
    {
        public string Id { get; set; }
        public string PatientID { get; set; }
        public string FormID { get; set; }
        public string DateOfVisit { get; set; }
        public string A1 { get; set; }
        public string A2 { get; set; }
        public string A3 { get; set; }
        public string A4 { get; set; }
        public string A5 { get; set; }
        public string A6 { get; set; }
        public string A7 { get; set; }
        public string A8 { get; set; }
        public string A9 { get; set; }
        public string A10 { get; set; }
        public string A11 { get; set; }
        public string SurveyID { get; set; }
        public Nullable<int> TotalScore { get; set; }
    
        public virtual Form Form { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
