//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnockAndCheckHF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Checkups = new HashSet<Checkup>();
        }
    
        public string PatientID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DoB { get; set; }
        public string PhoneNumber { get; set; }
        public string StreetAddress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string PrefferedDay { get; set; }
        public string PrefferedTime { get; set; }
        public string StartDate { get; set; }
        public string StartTime { get; set; }
        public string EmergencyFirstName { get; set; }
        public string EmergencyLastName { get; set; }
        public string EmergencyAddress { get; set; }
        public string EmergencyPhoneNumber { get; set; }
        public string EmergencyCity { get; set; }
        public string EmergencyState { get; set; }
        public string EmergencyZip { get; set; }
        public string EmergencyRelationship { get; set; }
        public string EnrollingCareGiver { get; set; }
        public string PrimaryCareGiver { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Checkup> Checkups { get; set; }
    }
}
